version: 2

linters:
  enable:
    - govet
    - revive
    - staticcheck
    - ineffassign
    - unused
    - misspell

  settings:
    revive:
      rules:
        - name: dot-imports
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - allowed-packages: ["github.com/onsi/ginkgo/v2", "github.com/onsi/gomega"]

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
