version: '3'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
    ports:
      - "9090:9090"
    depends_on:
      - static-metrics

  static-metrics:
    image: nginx:alpine
    container_name: static-metrics
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:z
      - ./metrics.txt:/usr/share/nginx/html/metrics:z
